# This search strategy does a multi_match prefix query to search in an optimized prefix search
# field which is filled with sensible data of the searchable nodes.

PunktDe:
  Elastic:
    NodeSearchService:
      logRequests: true
      fallBackOnEmptyResult: false
      searchStrategies:
        position: end
        titlePrefix:
          condition: '${Array.indexOf(searchNodeTypes, "Neos.Neos:Document") != -1}'
          request:
            query:
              bool:
                filter:
                  bool:
                    minimum_should_match: 1
                    should:
                      - multi_match:
                          query: ARGUMENT_TERM
                          type: bool_prefix
                          fields: ['punktde_node_search', 'punktde_node_search._2gram', 'punktde_node_search._3gram']
                    must:
                      - terms:
                          neos_type_and_supertypes: ARGUMENT_SEARCHNODETYPES
                      - term:
                          neos_parent_path : ARGUMENT_STARTINGPOINT
                    must_not:
                      - term:
                          neos_hidden: true
            _source:
              - neos_path
            size: 20
